services:
  mongo:
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/var/lib/mongo/data
    environment:
      - REPLICA_SET_NAME=db-rs
      - USERNAME=root
      - PASSWORD=12345
    ports:
      - "27001:27001"
      - "27002:27002"
      - "27003:27003"
    image: flqw/docker-mongo-local-replicaset

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data: